# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 538c3a6a73374ce60481d0c388c127b47ec5197c725281bc9f9ee8e8f4670b2cb42822e7c6a627bdeec8e70c454febef8c8d2bab9fe44d15b14a100442d95444

test:
  secret_key_base: f5ceb1c9ed2c2513d7106c98e7ec40686b7a83b66712345218d6ab08596b7d8c1fdbfb9dbad55428e392a319e961df524dbdcb17b8e403a7c27c98f4a2b797f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
